[package]
name = "performance_enhance"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"

[dev-dependencies]
criterion = "0.5.1"
rstest = "0.25.0"

[[bench]]
name = "mov_instruction_bench"
harness = false
